name: Bug report
description: Report a bug
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide enough detail to reproduce.
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "e.g. 0.1.0"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Redact secrets before pasting.
      render: text
    validations:
      required: false
